version: '3.8'

services:
  php-fpm:
    container_name: api-php-fpm
    build:
      context: docker/php-fpm
      args:
        DOCKER_PHP_ENABLE_XDEBUG: 'off'
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - XDEBUG_CONFIG="remote_host=host.docker.internal remote_enable=1"
      - PHP_IDE_CONFIG="serverName=docker-server"
    volumes:
      - ./:/var/www
    networks:
      - apinetwork

  nginx:
    container_name: api-nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    networks:
      - apinetwork

  encore:
    container_name: api-encore
    build:
      context: ./docker/encore
      args:
        USER_ID: ${UID-1000}
    volumes:
      - ./:/var/www
      - /var/www/vendor
    networks:
      - apinetwork
    tty: true
networks:
  apinetwork:
